version: "3.8"

services:
  php_yii2_app:
    image: akashkoche/php-yii2-app:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    ports:
      - "8080:80"
    networks:
      - yii2_net
    environment:
      - APP_ENV=production

  nginx:
    image: nginx:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php_yii2_app
    networks:
      - yii2_net

networks:
  yii2_net:
    driver: overlay
