version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  php_yii2_app:
    build: ./php-yii2-app
    networks:
      - app_net
    deploy:
      replicas: 1

networks:
  app_net:
    driver: overlay
