---
- name: Setup Docker Swarm Manager and NGINX
  hosts: swarm_manager
  become: yes

  tasks:
    - name: Install necessary packages
      apt:
        name:
          - docker.io
          - docker-compose
          - nginx
        state: present
        update_cache: yes

    - name: Start and enable Docker
      systemd:
        name: docker
        enabled: true
        state: started

    - name: Initialize Docker Swarm
      shell: docker swarm init
      args:
        creates: /tmp/.docker_swarm_initialized

    - name: Create marker file
      file:
        path: /tmp/.docker_swarm_initialized
        state: touch
