name: Build and Deploy Yii2 App

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/php-yii2-app:latest ./deployment/php-yii2-app
          docker push ${{ secrets.DOCKER_USERNAME }}/php-yii2-app:latest

      - name: Run Ansible Deployment
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu
            git clone https://github.com/AkashKoche/PHP-Yii2-Application.git
            ansible-playbook -i "localhost," ./PHP-Yii2-Application/deployment/deploy-stack.yml
